### PR TITLE
remove jupyter utils since the plan is changed to put common widget utils inside deck.gl

### PR DESCRIPTION
**Pull request by kenns29**

### CODE REVIEW

**Comment by Firenze11** [comment]
Why do we put widgets in deckgl? Any packages that would require widgets will have to depend on deckgl? Doesn't seem to be a good composition pattern imo.
Or, do you mean they are planning to put it in deckgl repo? In that case let's only migrate after the widget is ready to be installed in our codebase. I.E. when removing the old dependency we should make sure the new dependency is working.

**Comment by kenns29** [comment]
This folder was just for some widget related utils that can be shared by both us and the core-framework team. Since the core-framework team decided to put those common utils inside deck.gl, we should not keep a seperate copy here. We are going to have all the widget related dependencies sitting in this repo for a long time until the common widget is ready (till it is published and is ready to use). We just remove the legacy utils folder so that our repo stays clean.

**Comment by Firenze11** [comment]
> This folder was just for some widget related utils that can be shared by both us and the core-framework team. Since the core-framework team decided to put those common utils inside deck.gl, we should not keep a seperate copy here. We are going to have all the widget related dependencies sitting in this repo for a long time until the common widget is ready (till it is published and is ready to use). We just remove the legacy utils folder so that our repo stays clean.

In the meantime, what's the plan of migrating jupyter-related code from internal repo to here? I think that's how this migration could be tested.

**Comment by kenns29** [comment]
I plan to move the entire jupyter binding here until the mono repo structure is configured (this may happen in Wednesday). I want to make sure manifold works with ocular before I move any additional stuff to this repo. We can test this migration using the example folder first maybe, although I'm not sure if it is sufficient.

**Comment by chrisirhc** [comment]
See https://chris.beams.io/posts/git-commit/ on the use of the PR title versus the PR description.
Your title describes the change but doesn't describe the reason for it which is more important (since the PR's diff describes the change itself) as we look back in git blame/history.

**Comment by kenns29** [comment]
Close this PR because the issue has been addressed in another PR.

**Pull request closed without merging**
